# Generated by Django 5.2.7 on 2025-10-09 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Wagon', 'Wagon'), ('Pickup', 'Pickup')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='vehicles/')),
                ('available', models.BooleanField(default=True)),
                ('engine_size', models.CharField(blank=True, max_length=50, null=True)),
                ('transmission', models.CharField(blank=True, choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('CVT', 'CVT')], max_length=50, null=True)),
                ('fuel_type', models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=30, null=True)),
                ('drive_type', models.CharField(blank=True, max_length=30, null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_year', models.PositiveIntegerField(blank=True, null=True)),
                ('ownership_history', models.CharField(blank=True, max_length=100, null=True)),
                ('logbook_available', models.BooleanField(default=False)),
                ('insurance_valid', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('seating_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('interior_material', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.vehicle')),
            ],
        ),
    ]
